use_frameworks!

platform :ios, '9.0'

target 'XCExcelSimilarView_Example' do
  pod 'XCExcelSimilarView', :path => '../'

  target 'XCExcelSimilarView_Tests' do
    inherit! :search_paths

    
  end
end
